const js = document.querySelector("section") 
js.setAttribute("class", "featured")
const jss = document.querySelector("section.posts")
const dinoTail = document.createElement("article")
jss.append(dinoTail) 
//console.log(jss)
const dinoBody = document.createElement("img")
dinoTail.append(dinoBody)
//console.log(jss)
dinoBody.setAttribute("src", "./images/paul-gilmore-unsplash.jpg")
dinoBody.setAttribute("alt", "Image of a mountain in front of a lake.")
const dinoScales = document.createElement("h3")
dinoScales.innerText = "Stop Planning"
dinoTail.append(dinoScales)
const dinoTooth = document.createElement("p")
dinoTooth.innerText = ("You -- yes you! You're an over-planner, I can tell. It's time to stop planning so much and instead focusing on relaxing. Taking a break at all is so stressful these days; why add to the stress by overworking yourself?")
dinoTail.append(dinoTooth) 
const dinoToes = document.createElement("aside")
dinoTooth.append(dinoToes)
const dinoNail = document.createElement("p")
dinoToes.append(dinoNail) 
const dinoHeart = document.createElement("span")
dinoHeart.innerText = "4 Minutes" 
dinoNail.append(dinoHeart) 
const dinoBrain = document.createElement("strong")
dinoBrain.innerText = "Read Time"
dinoNail.append(dinoBrain) 
const dinoWing = document.createElement("a")
dinoWing.innerText = "Read more"
dinoWing.setAttribute("href", "#")
dinoNail.append(dinoWing)
const firstDinoArticle = document.querySelector('.art1')
const middleDinoArticle = document.querySelector('.art2')
firstDinoArticle.before(middleDinoArticle)